services:
  - type: web
    name: fairshare-backend
    env: node
    rootDir: FairShare/fairshare-backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGINS
        value: https://fairshar3.netlify.app
